// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type City struct {
	ID        int32
	Name      string
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
}

type DailyWeatherSummaryView struct {
	Bucket              interface{}
	CityID              int32
	AvgTemperature      pgtype.Numeric
	MaxTemperature      pgtype.Numeric
	MinTemperature      pgtype.Numeric
	AvgHumidity         pgtype.Numeric
	MaxHumidity         pgtype.Numeric
	MinHumidity         pgtype.Numeric
	AvgWindSpeed        pgtype.Numeric
	MaxWindSpeed        pgtype.Numeric
	MinWindSpeed        pgtype.Numeric
	DominantConditionID interface{}
}

type WeatherCondition struct {
	ID        int32
	Condition string
}

type WeatherDatum struct {
	Time        pgtype.Timestamptz
	CityID      int32
	ConditionID int32
	Temperature pgtype.Numeric
	FeelsLike   pgtype.Numeric
	Humidity    pgtype.Numeric
	WindSpeed   pgtype.Numeric
}
